### ISSUE TITLE
Create Product Section of the API

### ISSUE THREAD

**Issue by yeboah326** [yeboah326/Garage97#53]
**Tasks**
- [x] Create product model

**API Endpoints to work on**
- [x] Get all products
- [x] Get product by id
- [x] Create new product
- [x] Delete product by id
- [x] Update product by id
