### ISSUE TITLE
Create Stock section of the API

### ISSUE THREAD

**Issue by yeboah326** [yeboah326/Garage97#54]
**Tasks**

- [x] Create stock model
- [x] Create stockList model

**API Endpoints to create**
**Stock**
- [ ] Get stock by id
- [ ] Get all stock
- [ ] Create new stock
- [ ] Update stock by id
- [ ] Delete stock by id
- [ ] Delete all stock

**StockList**
- [ ] Get stockList by id
- [ ] Get all stockList
- [ ] Create new stockList
- [ ] Update stockList by id
- [ ] Delete stockList by id
- [ ] Delete all stockList
