### ISSUE TITLE
Create Sale section of the API

### ISSUE THREAD

**Issue by yeboah326** [yeboah326/Garage97#55]
**Tasks**

- [x] Create sale model
- [x] Create saleList model

**API Endpoints to create**
**Sale**
- [x] Get sale by id
- [x] Get all sale
- [x] Create new sale
- [x] Update sale by id
- [x] Delete sale by id
- [x] Delete all sale

**SaleList**

- [x] Get all saleList
- [x] Get saleList by id
- [x] Create new saleList
- [x] Update saleList by id
- [x] Delete saleList by id
- [x] Delete all saleList
